python ./ExDT.py \
    --env=walker2d-medium-replay-v2 \
    --tag=$tag \
    --pretrain_loss_fn=ODT-Value \
    --finetune_loss_fn=ODT \
    --learning_from_offline_dataset \
    --device=cuda:0  \
    --num_updates_per_pretrain_iter=10000 \
    --learning_rate=0.001 \
    --weight_decay=0.001 \
    --eval_context_length=5 \
    --eval_rtg=5000 \
    --online_rtg=10000 \
    --num_updates_per_online_iter=300 \
    --off_policy_tuning \
    --save_dir=pretrained_policy 